app: &app_base
  build: .
  ports:
    - "4077:4000"
  environment:
    DISPLAY: :0.0
  command: sleep 100000000000 # hack to keep container running in the background
  volumes:
    - .:/app
    - .hex:/root/.hex
    - .mix:/root/.mix
    - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
